### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by 1fexd** [lanesawyer/standardnotes-rs#97]

**Comment by lanesawyer** [comment]
Not really, I've been waiting on the documentation to be updated, since the last time I attempted doing work on it I followed their docs but they were out of date so nothing worked.

I just tried checking the docs again though and they seem to be gone (https://docs.standardnotes.com/specification/auth) and I'm not finding a similar page anywhere else on the site.

Without up-to-date specifications it's not really worth my time to try to make it work, unfortunately...

**Comment by 1fexd** [comment]
Sad to hear that, thanks for the fast response though.
